name: Package AI Voices
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARCHIVE_NAME: AI_Voices_${{github.ref_name}}
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 50

      - name: Build Archive
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a ${{env.ARCHIVE_NAME}}.7z "./FOMOD/*"

      - name: Create Release
        uses: notlmn/release-with-changelog@v3
        with:
          header: '### Changelog'
          include-hash: true
          include-range: true
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Upload to Github
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: ${{env.ARCHIVE_NAME}}.7z
